### ISSUE TITLE
quicksilver flask not being used while cycloning

### ISSUE THREAD

**Issue by lelefi** [sychotixdev/BasicFlaskRoutine#12]
hi,
my quicksilver speed flask only triggers when im not cyclonig. when im cycloning it wont cast at all

**Comment by IlliumIv** [comment]
@lelefi , hey.
Because cycloning != moving.
U can temporary use [my fork](https://github.com/IlliumIv/BasicFlaskRoutine) of plugin, i added toggle to allow use speed flasks while cycloning. Warning: PluginUpdater will be update plugin to original repo (without my changes).

P.S. sry for my eng.

**Comment by lelefi** [comment]
@IlliumIv thank you, im gonna try this :)
edit: works like a charm, thank you!!

**Comment by IlliumIv** [comment]
@lelefi np, i just love Cyclone)
I updated repo, added counting of nearby monsters (like defensive\offensive flasks), y can reloaded plugin to use it.

**Comment by lelefi** [comment]
@IlliumIv cylcone is so good! just updated, thank you alot👍

**Comment by danteafk** [comment]
> @lelefi , hey.
> Because cycloning != moving.
> U can temporary use [my fork](https://github.com/IlliumIv/BasicFlaskRoutine) of plugin, i added toggle to allow use speed flasks while cycloning. Warning: PluginUpdater will be update plugin to original repo (without my changes).
> 
> P.S. sry for my eng.

 Hi,

how do I install this? Do I just copy everything into the basicflaskroutine folder? If I do that, does it not overwrite everything from the new updates?

**Comment by IlliumIv** [comment]
@danteafk 
Hi.
Just download BasicFlaskRoutine.dll and TreeRoutine.dll, and replace existing ones.

**Comment by danteafk** [comment]
> @danteafk
> Hi.
> Just download BasicFlaskRoutine.dll and TreeRoutine.dll, and replace existing ones.

does not work, replaced those, still does not use flask while spinning

**Comment by sychotixdev** [comment]
This should now be resolved with the latest version of ExileAPI
