### ISSUE TITLE
does compile but not working with exileapi

### ISSUE THREAD

**Issue by elvese** [sychotixdev/BasicFlaskRoutine#21]
![Screenshot_169](https://user-images.githubusercontent.com/18148889/64902552-6f803100-d6a9-11e9-9fa9-d7463ada1361.jpg)
![Screenshot_170](https://user-images.githubusercontent.com/18148889/64902555-8757b500-d6a9-11e9-8154-fae0d6b09f16.jpg)

**Comment by sychotixdev** [comment]
No need to have it compile BasicFlaskRoutine. The binary already exists. If there is an issue using the compiled project due to configuration files not being copied over, I'd say that is an issue with ExileApi itself. It should copy those files it shows you are missing to the compiled directory.
