### ISSUE TITLE
Syndicate Safehouses flagged as "hideout"

### ISSUE THREAD

**Issue by zathrath03** [sychotixdev/BasicFlaskRoutine#7]
Currently, Basic Flask routine is seeing Syndicate Safehouses as your "hideout," so it is not working in them unless the "Enable in Hideout" option is checked.

**Comment by sychotixdev** [comment]
This was a PoEHUD issue where basically we were checking if the name contained "Hideout". The safehouses are called "Syndicate Hideout," and thus returned true. This should now be fixed with a change zafaar pushed yesterday
