### ISSUE TITLE
Flask spam (3.5.2)

### ISSUE THREAD

**Issue by nartaki** [sychotixdev/BasicFlaskRoutine#9]
Not sure if this is on your side but Hud's **a1f839a** commit should've fixed the offsets on their side..Flasks are spamming after the update.

**Comment by sychotixdev** [comment]
Likely a HUD issue with some offset. Unless HUD makes changes to their core code or GGG makes major changes  to flasks, this plugin should always work.

**Comment by nartaki** [comment]
Silly me didn't realize they hadn't pushed the exe..My bad :)
